[config]
api_url = "http://127.0.0.1:8080/api"
source_folder = "~/omoide_sync/source"
archive_folder = "~/omoide_sync/archive"
log_level = "INFO"
log_filen = "omoide_sync.log"
cred_file = "omoide_sync_credentials.toml"
setup_filename = "setup.yaml"
supported_formats = [
    "png",
    "jpg",
    "jpeg",
    "webp",
]
skip_prefixes = ["_"]

[root]
init_collection = "raise"
final_collection = "move"
final_item = "move"
ephemeral = false
tags = []
limit = -1
